### ISSUE TITLE
Repo setup to-do list

### ISSUE THREAD

**Issue by mbonsma** [mbonsma/bike-ottawa#2]
Based on this [work-in-progress book chapter](https://github.com/merely-useful/r-rse/blob/main/chapters/10-community-involvement.Rmd), do these to get set up for collaboration:

- [ ] Add better description and purpose of project to README
- [ ] Add CODE_OF_CONDUCT.md
- [ ] Add CONTRIBUTING.md
- [ ] Create issue labels
- [ ] Create a roadmap (in issues)
